Repository Lordpluha/GameBlog, pull requests merged in 2023-12, with the labels that each got.

#10 Features/set up prisma
  nest-server/.env.example
  nest-server/package.json
  nest-server/prisma/migrations/20231218171236_user/migration.sql
  nest-server/prisma/migrations/migration_lock.toml
  nest-server/prisma/schema.prisma
  nest-server/src/app.module.ts
  nest-server/src/common/env.validation.ts
  nest-server/src/common/prisma.service.ts
  nest-server/src/configs/env.config.ts
  nest-server/src/main.ts
  nest-server/yarn.lock
Labels: feauture

#17 Create issue and bug templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: docs

#18 Create useFetching.tsx
  client/src/components/hooks/useFetching.tsx
Labels: feauture

#20 Feauture/jwt auth
  nest-server/.env.example
  nest-server/.prettierrc
  nest-server/package.json
  nest-server/src/app.module.ts
  nest-server/src/auth/auth.controller.ts
  nest-server/src/auth/auth.module.ts
  nest-server/src/auth/auth.service.ts
  nest-server/src/auth/constants/auth.constants.ts
  nest-server/src/auth/constants/error.auth.constants.ts
  nest-server/src/auth/decorators/access-jwt.decorator.ts
  nest-server/src/auth/decorators/cookie.decorator.ts
  nest-server/src/auth/decorators/refresh-jwt.decorator.ts
  nest-server/src/auth/dto/jwt-generate.dto.ts
  nest-server/src/auth/dto/login.dto.ts
  nest-server/src/auth/dto/registration.dto.ts
  nest-server/src/auth/dto/return-data.dto.ts
  nest-server/src/auth/strategies/jwt-access.strategy.ts
  nest-server/src/auth/strategies/jwt-refresh.strategy.ts
  nest-server/src/auth/token.service.ts
  nest-server/src/common/env.validation.ts
  nest-server/src/common/prisma.service.ts
  nest-server/src/configs/env.config.ts
  nest-server/src/configs/swagger.config.ts
  nest-server/src/main.ts
  nest-server/src/user/constants/error.constants.user.ts
  nest-server/src/user/decorators/user.decorator.ts
  nest-server/src/user/dto/create-user.dto.ts
  nest-server/src/user/dto/update-user.dto.ts
  nest-server/src/user/user.controller.ts
  nest-server/src/user/user.module.ts
  nest-server/src/user/user.service.ts
  nest-server/test/app.e2e-spec.ts
  nest-server/yarn.lock
Labels: feauture

#32 Features/21 create pages
  client/src/App.tsx
  client/src/pages/BlogsPage.tsx
  client/src/pages/CheatsPage.tsx
  client/src/pages/ErrorPage.tsx
  client/src/pages/GamesPage.tsx
  client/src/pages/Layout.tsx
  client/src/pages/NewsPage.tsx
  client/src/pages/ReadPage.tsx
  client/src/pages/StreamsPage.tsx
  client/src/pages/SupportPage.tsx
  client/src/pages/WatchPage.tsx
  client/src/routes/index.tsx
Labels: feauture, front

#34 Feauture/base service blog
  nest-server/.gitignore
  nest-server/package.json
  nest-server/prisma/migrations/20231224144454_blog/migration.sql
  nest-server/prisma/migrations/20231225132217_blog/migration.sql
  nest-server/prisma/migrations/20231225140126_slug/migration.sql
  nest-server/prisma/migrations/20231225143322_add/migration.sql
  nest-server/prisma/schema.prisma
  nest-server/seeder/seed.ts
  nest-server/src/app.module.ts
  nest-server/src/blog/blog.controller.ts
  nest-server/src/blog/blog.module.ts
  nest-server/src/blog/blog.service.ts
  nest-server/src/blog/constants/error.blogs.constants.ts
  nest-server/src/blog/dto/create-blog.dto.ts
  nest-server/src/blog/dto/pagination.blog.dto.ts
  nest-server/src/blog/dto/update-blog.dto.ts
  nest-server/src/common/pagination.query.dto.ts
  nest-server/src/file/file.module.ts
  nest-server/src/file/file.service.ts
  nest-server/src/user/dto/return-user.dto.ts
  nest-server/yarn.lock
Labels: back/nest

#44 Feature/base article
  nest-server/prisma/migrations/20231227121606_category_article_tags/migration.sql
  nest-server/prisma/migrations/20231227200222_category/migration.sql
  nest-server/prisma/migrations/20231227200811_category_1/migration.sql
  nest-server/prisma/migrations/20231227200845_category_2/migration.sql
  nest-server/prisma/migrations/20231227222902_article_verif/migration.sql
  nest-server/prisma/migrations/20231228112349_role/migration.sql
  nest-server/prisma/migrations/20231228121639_implicit/migration.sql
  nest-server/prisma/migrations/20231228215045_many_to_many_article_tags/migration.sql
  nest-server/prisma/migrations/20231229212235_rename/migration.sql
  nest-server/prisma/schema.prisma
  nest-server/seeder/seed.ts
  nest-server/src/app.module.ts
  nest-server/src/article/article.controller.ts
  nest-server/src/article/article.module.ts
  nest-server/src/article/article.service.ts
  nest-server/src/article/constants/error.article.constants.ts
  nest-server/src/article/decorators/swagger.article.decorator.ts
  nest-server/src/article/dto/create-article.dto.ts
  nest-server/src/article/dto/pagination.article.dto.ts
  nest-server/src/article/dto/return-article.dto.ts
  nest-server/src/article/dto/return-article.swagger.dto.ts
  nest-server/src/article/dto/update-article.dto.ts
  nest-server/src/auth/auth.controller.ts
  nest-server/src/auth/auth.service.ts
  nest-server/src/auth/decorators/swagger.auth.decorator.ts
  nest-server/src/auth/dto/jwt-generate.dto.ts
  nest-server/src/auth/dto/return-auth.swagger.dto.ts
  nest-server/src/auth/dto/return-data.dto.ts
  nest-server/src/category/category.controller.ts
  nest-server/src/category/category.module.ts
  nest-server/src/category/category.service.ts
  nest-server/src/category/constants/error.category.constants.ts
  nest-server/src/category/decorators/swagger.category.decorator.ts
  nest-server/src/category/dto/create-category.dto.ts
  nest-server/src/category/dto/pagination.category.dto.ts
  nest-server/src/category/dto/return-category.dto.ts
  nest-server/src/category/dto/return-category.swagger.dto.ts
  nest-server/src/category/dto/update-category.dto.ts
  nest-server/src/common/pagination.query.dto.ts
  nest-server/src/file/file.service.ts
  nest-server/src/role/decorators/role.decorator.ts
  nest-server/src/role/guards/role.guard.ts
  nest-server/src/role/role.enum.ts
  nest-server/src/tag/constants/error.tag.tag.ts
  nest-server/src/tag/decorators/swagger.tag.decorator.ts
  nest-server/src/tag/dto/create-tag.dto.ts
  nest-server/src/tag/dto/return-tag.dto.ts
  nest-server/src/tag/dto/return-tag.swagger.dto.ts
  nest-server/src/tag/dto/update-tag.dto.ts
  nest-server/src/tag/tag.controller.ts
  nest-server/src/tag/tag.module.ts
  nest-server/src/tag/tag.service.ts
  nest-server/src/user/dto/return-user.dto.ts
  nest-server/src/user/dto/return-user.swagger.dto.ts
  nest-server/tsconfig.build.json
Labels: feauture, back/nest
